version: '3.2'
services:
  mariadb:
    image: bitnami/mariadb-galera:latest
    restart: always
    network_mode: host
    volumes:
      - ./conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - ./data/mariadb-persistence:/bitnami/mariadb
    environment:
      #ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_GALERA_CLUSTER_NAME: "my_galera"
      MARIADB_GALERA_CLUSTER_ADDRESS: "gcomm://<BOOTSTRAP_NODE_IP>:4567,0.0.0.0:4567"
      MARIADB_GALERA_MARIABACKUP_USER: "my_mariabackup_user"
      MARIADB_GALERA_MARIABACKUP_PASSWORD: "my_mariabackup_password"
      MARIADB_USER: "my_user"
      MARIADB_PASSWORD: "my_password"
      MARIADB_DATABASE: "my_database"
      MARIADB_ROOT_USER: "admin"
      MARIADB_ROOT_PASSWORD: "password123"

# If you need to stop the MariaDB Galera cluster, ensure you stop the bootstrap node only after you have stopped all other nodes in the cluster. This ensure you do not loose any write that may have occurred while the nodes were being stopped.
# 如果你要停止MariaDB Galera 集群 , 你必須先所有其他節點 , 才能夠停止bootstrap node
